### ISSUE TITLE
crunsh output raise JavaScript error in browser

### ISSUE THREAD

**Issue by JozefJarosciak** [s-a/crunsh-single-page#1]
I am running crunsh on my app ([source code](https://github.com/JozefJarosciak/MortgageCalculatorAngular2)) and it successfully produces app.js, index.html and style.css.

However, when I place those 3 filed into a test folder on my domain: http://www.mortgagecalculator123.com/test/ it's not working.

I've inspected the page in Chrome and I am getting a following error:
**Uncaught ReferenceError: System is not defined (anonymous function).**

Any idea what I am doing wrong? Do you know how I can fixed this?

Thanks...

**Comment by s-a** [comment]
No idea . Crunsh simply concats each js file. You can switch this bool in source to create not mangled source. https://github.com/s-a/crunsh-single-page/blob/d42d6ae7a1267bdf12471bffcb1681463071385d/index.js#L81. this should help to identify from where your error occurs.
